package com.example.smartwastemanagement;

import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.text.ParseException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class AdminActivity extends AppCompatActivity {

    private FirebaseDatabase database;
    private DatabaseReference eventRef;
    EditText  manage_name,mobile,email,village_city,pin,username,password;
    Button submit;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_admin);

        database = FirebaseDatabase.getInstance();
        eventRef = database.getReference("Admin");

        manage_name=findViewById(R.id.Manage_Name);
        mobile=findViewById(R.id.Manage_mobile);
        email=findViewById(R.id.Manage_email);
        village_city=findViewById(R.id.Manage_village_city);
        pin=findViewById(R.id.Manage_pin);
        username=findViewById(R.id.Manage_username);
        password=findViewById(R.id.Manage_pass);
        submit=findViewById(R.id.Manage_add_btn);
        submit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String m_name1 = manage_name.getText().toString().trim();
                String mobile1 = mobile.getText().toString().trim();
                String email1 = email.getText().toString().trim();
                String village_city1 = village_city.getText().toString().trim();
                String pin1 = pin.getText().toString().trim();
                String username1 = username.getText().toString().trim();
                String password1 = password.getText().toString().trim();


                if (TextUtils.isEmpty(m_name1)) {
                    manage_name.setError("Please Enter Management name");
                    manage_name.requestFocus();
                    return;
                }
                if (TextUtils.isEmpty(mobile1)) {
                    mobile.setError("Please Enter Mobile");
                    mobile.requestFocus();
                    return;
                }
                if (TextUtils.isEmpty(email1)) {
                    email.setError("Please Enter Email");
                    email.requestFocus();
                    return;
                }
                if (TextUtils.isEmpty(village_city1)) {
                    village_city.setError("Please Enter Village/City");
                    village_city.requestFocus();
                    return;
                }
                if (TextUtils.isEmpty(pin1)) {
                    pin.setError("Please Enter Pin");
                    pin.requestFocus();
                    return;
                }
                String usernameRegex2 = ".*\\$.*";

                if (!username1.matches(usernameRegex2)) {
                    username.setError("Username must contain at least one '$' character.");
                    username.requestFocus();
                    return;
                }
                if (TextUtils.isEmpty(password1)) {
                    password.setError("Please Enter Password");
                    password.requestFocus();
                    return;
                }
                try {
                    // Generate a unique ID using Firebase's push() method
                    DatabaseReference newEventRef = eventRef.push();
                    String newAdminId = newEventRef.getKey();  // Get the unique ID generated by push()

                    // Prepare event data
                    Map<String, Object> adminData = new HashMap<>();
                    adminData.put("managementName", m_name1);
                    adminData.put("managementMobile", mobile1);
                    adminData.put("managementEmail", email1);
                    adminData.put("managementVillageCity", village_city1);
                    adminData.put("managementPin", pin1);
                    adminData.put("managementUsername", username1);
                    adminData.put("managementPassword", password1);

                    // Store the event data under the new unique ID
                    newEventRef.setValue(adminData);

                    // Create a new node "AdminIds" and add the generated unique ID
                    DatabaseReference adminIdsRef = database.getReference("EventRegisterManagement");
                    adminIdsRef.child(newAdminId).setValue(true);  // Store the unique ID with a value of 'true' (or any value)

                    // Notify the user
                    Toast.makeText(AdminActivity.this, "Management added successfully!", Toast.LENGTH_SHORT).show();
                } catch (Exception e) {
                    e.printStackTrace();
                    Toast.makeText(AdminActivity.this, "Management not added", Toast.LENGTH_SHORT).show();
                }
            }
        });


    }
}